ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 0
warningCode = 0

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.if-return]
[rule.increment-decrement]
[rule.var-naming]
[rule.var-declaration]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.superfluous-else]
[rule.errorf]
[rule.empty-block]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.redefines-builtin-id]
[rule.cyclomatic]
  arguments = [10]
[rule.cognitive-complexity]
  arguments = [15]
[rule.get-return]
[rule.deep-exit]
[rule.flag-parameter]
[rule.modifies-value-receiver]
[rule.unhandled-error]
  arguments = ["fmt.Fprintf", "fmt.Fprintln", "fmt.Printf", "fmt.Println"]
[rule.early-return]
[rule.defer]
